// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProManSystem.Data;

#nullable disable

namespace ProManSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251212025743_AddSalesInvoices")]
    partial class AddSalesInvoices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ProManSystem.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activite")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Adresse")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CA_HT")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CA_TTC")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeClient")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateRadiation")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstRadie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatriculeFiscal")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroIdentification")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroRC")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeIdentification")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ProManSystem.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeProduit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CoutProduction")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Marge")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixVente")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockActuel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockMin")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ProManSystem.Models.ProductRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantiteNecessaire")
                        .HasColumnType("TEXT");

                    b.Property<int>("RawMaterialId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RawMaterialId");

                    b.ToTable("ProductRecipes");
                });

            modelBuilder.Entity("ProManSystem.Models.PurchaseInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFacture")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstPayee")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontantHT")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantPaye")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantTTC")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantTVA")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroFacture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Reste")
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseInvoices");
                });

            modelBuilder.Entity("ProManSystem.Models.PurchaseInvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontantLigne")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("TEXT");

                    b.Property<int>("PurchaseInvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("TEXT");

                    b.Property<int>("RawMaterialId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseInvoiceId");

                    b.HasIndex("RawMaterialId");

                    b.ToTable("PurchaseInvoiceLines");
                });

            modelBuilder.Entity("ProManSystem.Models.RawMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeMatiere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PMAPA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockActuel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockInitial")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockMin")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("RawMaterials");
                });

            modelBuilder.Entity("ProManSystem.Models.SalesInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFacture")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstPayee")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontantHT")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantPaye")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantTTC")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantTVA")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroFacture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Reste")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("SalesInvoices");
                });

            modelBuilder.Entity("ProManSystem.Models.SalesInvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontantLigne")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalesInvoiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesInvoiceId");

                    b.ToTable("SalesInvoiceLines");
                });

            modelBuilder.Entity("ProManSystem.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activite")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Adresse")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeFournisseur")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Dette")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstActif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatriculeFiscal")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroIdentification")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroRC")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalAchats")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeIdentification")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("ProManSystem.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstPredefined")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("ProManSystem.Models.ProductRecipe", b =>
                {
                    b.HasOne("ProManSystem.Models.Product", "Product")
                        .WithMany("ProductRecipes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProManSystem.Models.RawMaterial", "RawMaterial")
                        .WithMany("ProductRecipes")
                        .HasForeignKey("RawMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("RawMaterial");
                });

            modelBuilder.Entity("ProManSystem.Models.PurchaseInvoice", b =>
                {
                    b.HasOne("ProManSystem.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ProManSystem.Models.PurchaseInvoiceLine", b =>
                {
                    b.HasOne("ProManSystem.Models.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("Lignes")
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProManSystem.Models.RawMaterial", "RawMaterial")
                        .WithMany()
                        .HasForeignKey("RawMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseInvoice");

                    b.Navigation("RawMaterial");
                });

            modelBuilder.Entity("ProManSystem.Models.RawMaterial", b =>
                {
                    b.HasOne("ProManSystem.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ProManSystem.Models.SalesInvoice", b =>
                {
                    b.HasOne("ProManSystem.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProManSystem.Models.SalesInvoiceLine", b =>
                {
                    b.HasOne("ProManSystem.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProManSystem.Models.SalesInvoice", "SalesInvoice")
                        .WithMany("Lignes")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("ProManSystem.Models.Product", b =>
                {
                    b.Navigation("ProductRecipes");
                });

            modelBuilder.Entity("ProManSystem.Models.PurchaseInvoice", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("ProManSystem.Models.RawMaterial", b =>
                {
                    b.Navigation("ProductRecipes");
                });

            modelBuilder.Entity("ProManSystem.Models.SalesInvoice", b =>
                {
                    b.Navigation("Lignes");
                });
#pragma warning restore 612, 618
        }
    }
}
